name = "dither-spark-studio"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[build]
  command = "npm run build"
  publish = "dist"

[build.upload]
  format = "modules"
  main = "dist/index.html"
  rules = [
    { type = "Favicon", glob = "**/*.ico" },
    { type = "Headers", glob = "**/*.html", headers = { "Cache-Control" = "public, max-age=0, must-revalidate" } },
    { type = "Headers", glob = "assets/**/*", headers = { "Cache-Control" = "public, max-age=31536000, immutable" } }
  ]

[[routes]]
  src = "/.*"
  dest = "/index.html"
  status = 200
